# Generated by Django 4.2.5 on 2023-09-23 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sixdegreesgame", "0001_add_song_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song",
            old_name="song_name",
            new_name="name",
        ),
    ]
